Readd mode arguments to openni2.launch
ros-drivers/openni2_camera pull request #102
Opened 2020-12-01 15:02 UTC by v-lopez

These args were lost on https://github.com/ros-drivers/openni2_camera/commit/576b616023175f75028430f47c2f72184cfa4587

Afaik there's no other way to specify at startup the mode, and changing the mode after the node is running via dynamic reconfigure is something that we'd like to avoid.

2021-01-18 08:54 UTC, MatthijsBurgh commented
I think it is good to restore this. I suggest keep the documentation line as well as described in https://github.com/ros-drivers/openni2_camera/commit/576b616023175f75028430f47c2f72184cfa4587#diff-f75072e949914a0b3f6d5ac4c7307380d93396eadd46d0ddf4c9a98fae6f3e83L21-L24

I suggest to update the `tf_prefix` launch file as well to keep these in sync.

Might be best to rebase and merge into `noetic-devel`

2023-02-17 07:43 UTC, 130s commented
Thank you for the contribution.
I took a liberty to change the target branch to `ros1`, which might have not existed when this PR was opened.

I won't have a room to take a closer look nor test myself. Nor have I time to address the suggestion https://github.com/ros-drivers/openni2_camera/pull/102#issuecomment-762093262. That said, with @MatthijsBurgh comment, I'm inclined to merging (and depend on the OSS community to test). In a few days I might merge unless we'll receive objections.

2023-02-17 08:59 UTC, MatthijsBurgh commented on openni2_launch/package.xml
> +<package format="3">
```suggestion
<?xml version="1.0"?>
<?xml-model
  href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
```

2023-02-17 09:02 UTC, MatthijsBurgh commented on openni2_launch/launch/openni2.launch
> +  <arg name="color_mode"            default="5" />
```suggestion
  <!-- Resolution and FPS setting for each channel -->
  <arg name="color_mode"            default="5" />
```

2023-02-17 09:03 UTC, MatthijsBurgh requested changes
@130s As mentioned in my previous comment. We should also update `openni2_tf_prefix.launch` before merging this one.
When we have updated that file too. I will approve.
(I don't have write access in this organization, so I can't edit this PR.)

2025-05-21 12:28 UTC, mikeferguson commented
ROS 1 Noetic is going EOL and no longer accepting new changes

2025-05-21 12:28 UTC, closed without merging